spring:
  datasource:
    username: root
    password: root@123
    url: jdbc:mysql://localhost:3306/cms
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  config:
    import: optional:configserver:localhost:8071

eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

rabbitmq:
  host: "localhost"
  port: 5672
  username: "guest"
  password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"

current:
  environment: local
