# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: oms-deployment
serviceName: oms
appLabel: oms
appName: oms

replicaCount: 1

image:
  repository: mani12345/oms
  tag: r6

containerPort: 8082

service:
  type: ClusterIP
  port: 8082
  targetPort: 8082

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resouceserver_enabled: false
otel_enabled: true
kafka_enabled: false
