# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: gatewayserver-deployment
serviceName: gatewayserver
appLabel: gatewayserver
appName: gatewayserver

replicaCount: 1

image:
  repository: mani12345/gatewayserver
  tag: s14

containerPort: 8888

service:
  type: LoadBalancer
  port: 8888
  targetPort: 8888

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: false
resouceserver_enabled: true
otel_enabled: true
kafka_enabled: false
