apiVersion: v1
kind: Service
metadata:
  name: keycloak18-headless
spec:
  clusterIP: None
  selector:
    app: keycloak18
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
    - name: jgroups
      port: 8080
      protocol: TCP
      targetPort: jgroups
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak18
  labels:
    app: keycloak18
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: keycloak18
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak18
  labels:
    app: keycloak18
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak18
  template:
    metadata:
      labels:
        app: keycloak18
    spec:
      containers:
        - name: keycloak18
          image: quay.io/keycloak/keycloak:18.0.0
          args: ["start-dev"]
          env:
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin"
            - name: KC_PROXY
              value: "edge"
            - name: KC_DB
              value: "mysql"
            - name: KC_DB_URL
              value: "jdbc:mysql://mysqlhost:3306/keycloakonquarkus"
            - name: KC_DB_USERNAME
              value: "mysqluser"
            - name: KC_DB_PASSWORD
              value: "mysqlpassword"
            - name: KC_HEALTH_ENABLED
              value: "true"
            - name: KC_METRICS_ENABLED
              value: "true"
            - name: KC_FEATURES
              value: "token-exchange,preview,scripts"
            - name: KC_HTTP_RELATIVE_PATH
              value: "/auth"
            - name: KC_SPI_ADMIN_REALM
              value: "yourmasterrealmname"
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /auth/realms/techapps
              port: 8080
