apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:24.0.1
          args: ["start-dev"]
          env:
            - name: DB_VENDOR
              valueFrom:
                configMapKeyRef:
                  name: techapps-configmap
                  key: DB_VENDOR
            - name: DB_ADDR
              valueFrom:
                configMapKeyRef:
                  name: techapps-configmap
                  key: DB_ADDR
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: techapps-configmap
                  key: DB_PORT
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: techapps-configmap
                  key: DB_DATABASE
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: techapps-configmap
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: techapps-configmap
                  key: DB_PASSWORD
            - name: KEYCLOAK_ADMIN
              valueFrom:
                configMapKeyRef:
                  name: techapps-configmap
                  key: KEYCLOAK_USER
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: techapps-configmap
                  key: KEYCLOAK_ADMIN_PASSWORD
          ports:
            - containerPort: 8080
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  selector:
    app: keycloak
  type: NodePort
  ports:
    - name: http
      port: 7080
      targetPort: 8080
