apiVersion: v1
kind: ConfigMap
metadata:
  name: techapps-configmap
data:
  SPRING_PROFILES_ACTIVE: cloud
  SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8761/eureka/"
  CONFIGSERVER_APPLICATION_NAME: configserver
  EUREKA_APPLICATION_NAME: eurekaserver
  CMS_APPLICATION_NAME: cms
  OMS_APPLICATION_NAME: oms
  GATEWAY_APPLICATION_NAME: gatewayserver
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: admin
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI: "http://keycloak:7080/realms/master/protocol/openid-connect/certs"
  apiVersion: v1
  KEYCLOAK_USER: admin
  KEYCLOAK_PASSWORD: admin-password
  DB_VENDOR: "mysql"
  DB_CMS_ADDR: jdbc:mysql://gfl-k8s-db.cyuanxrjfhqn.ap-south-1.rds.amazonaws.com:3306/cms
  DB_OMS_ADDR: jdbc:mysql://gfl-k8s-db.cyuanxrjfhqn.ap-south-1.rds.amazonaws.com:3306/oms
  DB_KEYCLOAK_ADDR: jdbc:mysql://gfl-k8s-db.cyuanxrjfhqn.ap-south-1.rds.amazonaws.com:3306/keycloak
  DB_PORT: "3306"
  DB_DATABASE: keycloak
  DB_USER: "admin"
  DB_PASSWORD: "gflk8sdb"
  OMS_URL: http://oms:8082
