apiVersion: apps/v1
kind: Deployment
metadata:
  name: oms-deployment
  labels:
    app: oms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oms
  template:
    metadata:
      labels:
        app: oms
    spec:
      containers:
        - name: oms
          image: mani12345/oms:s14
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: techapps-configmap
                  key: CMS_APPLICATION_NAME
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: techapps-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: techapps-configmap
                  key: SPRING_CONFIG_IMPORT
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: techapps-configmap
                  key: DB_OMS_ADDR
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: techapps-configmap
                  key: DB_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: techapps-configmap
                  key: DB_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: oms
spec:
  selector:
    app: oms
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
