apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-deployment
  labels:
    app: cms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cms
  template:
    metadata:
      labels:
        app: cms
    spec:
      containers:
        - name: cms
          image: mani12345/cms:r4
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: techapps-configmap
                  key: CMS_APPLICATION_NAME
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: techapps-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: techapps-configmap
                  key: SPRING_CONFIG_IMPORT
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: techapps-configmap
                  key: DB_CMS_ADDR
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: techapps-configmap
                  key: DB_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: techapps-configmap
                  key: DB_PASSWORD
            - name: OMS_URL
              valueFrom:
                configMapKeyRef:
                  name: techapps-configmap
                  key: OMS_URL

---
apiVersion: v1
kind: Service
metadata:
  name: cms
spec:
  selector:
    app: cms
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
