apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: spring-cloud-kubernetes-discoveryserver
      name: spring-cloud-kubernetes-discoveryserver
    spec:
      ports:
        - name: http
          port: 80
          targetPort: 8761
      selector:
        app: spring-cloud-kubernetes-discoveryserver
      type: ClusterIP

  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      labels:
        app: spring-cloud-kubernetes-discoveryserver
      name: spring-cloud-kubernetes-discoveryserver

  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: namespace-reader
      namespace: default
    rules:
      - apiGroups: ["", "discovery.k8s.io"]
        resources:
          [
            "configmaps",
            "pods",
            "services",
            "endpoints",
            "secrets",
            "endpointslices",
          ]
        verbs: ["get", "list", "watch"]

  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: namespace-reader-binding
      namespace: default
    subjects:
      - kind: ServiceAccount
        name: spring-cloud-kubernetes-discoveryserver
        namespace: default
    roleRef:
      kind: Role
      name: namespace-reader
      apiGroup: rbac.authorization.k8s.io

  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: spring-cloud-kubernetes-discoveryserver-deployment
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: spring-cloud-kubernetes-discoveryserver
      template:
        metadata:
          labels:
            app: spring-cloud-kubernetes-discoveryserver
        spec:
          serviceAccountName: spring-cloud-kubernetes-discoveryserver
          containers:
            - name: spring-cloud-kubernetes-discoveryserver
              image: springcloud/spring-cloud-kubernetes-discoveryserver:3.1.0
              imagePullPolicy: IfNotPresent
              readinessProbe:
                httpGet:
                  port: 8761
                  path: /actuator/health/readiness
                initialDelaySeconds: 10
                periodSeconds: 30
              livenessProbe:
                httpGet:
                  port: 8761
                  path: /actuator/health/liveness
                initialDelaySeconds: 10
                periodSeconds: 30
              ports:
                - containerPort: 8761
